name: Jalankan Ngrok

on: 
  push:
    branches:
      - main  # Workflow akan berjalan ketika ada push ke branch 'main'

jobs:
  jalankan-ngrok:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Mengambil kode dari repository

    - name: Install ngrok
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin/  # Menginstall ngrok

    - name: Run ngrok on port 80
      run: |
        nohup ngrok http 80 &  # Menjalankan ngrok di port 80 di latar belakang

    - name: Display ngrok public URL
      run: |
        sleep 5  # Menunggu sebentar hingga ngrok siap
        curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'  # Menampilkan URL publik ngrok
